name: fstar
description: 繁星课程表

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 2.1.4+41

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  dio: ^4.0.0
  hive_flutter: ^1.1.0
  hive: ^2.0.4
  #  fluro: ^1.7.8
  flutter_easyloading: ^3.0.0
  awesome_dialog: ^2.1.0
  html: ^0.15.0
  image_picker: ^0.8.2
  # null-safety
  install_plugin:
    git: https://github.com/mitchross/flutter_install_plugin
    # 临时替换
  flutter_neumorphic:
    git: https://github.com/alionour/Flutter-Neumorphic
  provider: ^5.0.0
  flutter_staggered_animations: ^1.0.0
  flutter_displaymode: ^0.3.2
  flutter_inappwebview: ^5.3.2
  device_info: ^2.0.2
  logger: ^1.0.0
  flutter_colorpicker: ^0.5.0
  # null-safety
  flutter_material_color_picker:
    git: https://github.com/Bwolfs2/flutter_material_color_picker
  tuple: ^2.0.0
  image_cropper: ^1.4.1
  path_provider: ^2.0.2
  url_launcher: ^6.0.9
  font_awesome_flutter: ^9.1.0
  pull_to_refresh: ^2.0.0
  flutter_rounded_date_picker: ^2.0.2
  flutter_screenutil: ^5.0.0+2
  just:
    git: https://github.com/mikai233/just.git
  toggle_switch: ^1.2.0
  package_info: ^2.0.2
  #  permission_handler: ^5.0.1+2
  image_gallery_saver: ^1.6.9
  #  animations: ^1.1.2
  flutter_markdown: ^0.6.3
  excel: ^2.0.0-null-safety-3
  shared_preferences: ^2.0.6
  crypto: ^3.0.1
  photo_view: ^0.12.0
  flutter_interactional_widget:
    git: https://github.com/mikai233/flutter_interactional_widget

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.6
  hive_generator: ^1.1.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
